package encode

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/GH-Jaider/foley/internal/execx"
)

// padEven pads odd dimensions up to even ones: yuv420p (mp4/webm) needs
// them and scaled terminal cells can legitimately be odd (19px at 2x).
const padEven = "pad=ceil(iw/2)*2:ceil(ih/2)*2"

// gifFilter is the VHS-proven palettegen/paletteuse recipe: a palette
// computed from the actual frames beats the fixed 256-color web palette
// by a mile on terminal content. Stats stay in full mode on purpose:
// diff mode weights colors by CHANGING pixels, which starved rare-but-
// distinct hues (a color emoji appearing once lost its red to the
// nearest text-blend gray). reserve_transparent frees the alpha slot —
// terminal frames are always opaque.
const gifFilter = "split[a][b];[a]palettegen=reserve_transparent=0[p];[b][p]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle"

// GIF assembles framesDir (a closed PNGSink) into an animated GIF. The
// last frame's delay cannot come from pts deltas (the -t cut removes the
// marker entry), so it is passed explicitly via -final_delay — computed
// from the recording's own last duration, never a fixed default.
func GIF(ctx context.Context, framesDir, outPath string) error {
	_, last, err := readManifest(framesDir)
	if err != nil {
		return err
	}
	return assemble(ctx, framesDir, outPath,
		"-vf", gifFilter,
		"-loop", "0",
		"-final_delay", strconv.FormatInt(centiseconds(last), 10),
	)
}

// centiseconds rounds d to GIF's delay unit; the format cannot express
// sub-centisecond delays, so anything shorter becomes the 1cs floor.
func centiseconds(d time.Duration) int64 {
	cs := int64((d + 5*time.Millisecond) / (10 * time.Millisecond))
	if cs < 1 {
		return 1
	}
	return cs
}

// MP4 assembles framesDir into an H.264 MP4 (yuv420p + faststart: plays
// everywhere, streams instantly).
func MP4(ctx context.Context, framesDir, outPath string) error {
	return assemble(ctx, framesDir, outPath,
		"-vf", padEven,
		"-c:v", "libx264",
		"-pix_fmt", "yuv420p",
		"-crf", "18",
		"-movflags", "+faststart",
	)
}

// WebM assembles framesDir into a VP9 WebM.
func WebM(ctx context.Context, framesDir, outPath string) error {
	return assemble(ctx, framesDir, outPath,
		"-vf", padEven,
		"-c:v", "libvpx-vp9",
		"-pix_fmt", "yuv420p",
		"-crf", "32",
		"-b:v", "0",
	)
}

// assemble runs one ffmpeg pass over the manifest. The concat demuxer
// resolves the frame files relative to the manifest's own directory, and
// -fps_mode vfr carries the exact per-frame durations into the output
// timestamps. The manifest's trailing repeated file (the quirk that makes
// the last duration effective) would surface as a duplicate final frame
// under vfr — cutting the output at the exact total duration drops it:
// the duplicate sits precisely AT the boundary while the last real frame
// keeps its full span.
func assemble(ctx context.Context, framesDir, outPath string, codecArgs ...string) error {
	total, _, err := readManifest(framesDir)
	if err != nil {
		return err
	}
	args := []string{
		"-hide_banner", "-loglevel", "error", "-y",
		"-f", "concat",
		// The per-file `option` directive requires unsafe mode. Safe mode
		// guards against untrusted list files; this manifest and every
		// name in it are generated by PNGSink, never user input.
		"-safe", "0",
		"-i", filepath.Join(framesDir, manifestName),
		"-fps_mode", "vfr",
		"-t", fmt.Sprintf("%.6f", total.Seconds()),
		// Reproducibility: without these, mp4 embeds `Lavf/Lavc<version>`
		// tags and webm stamps Muxing/WritingApp with the ffmpeg version —
		// the same recording would differ byte-for-byte across ffmpeg
		// installs for no visual reason (probed live: Lavf62.12.101 in
		// both containers). bitexact also pins mp4's creation_time to the
		// epoch instead of "now". The CODEC bitstream still legitimately
		// depends on the encoder library's version — full byte-identity
		// holds per pinned ffmpeg, which is why the PNG frames, not the
		// containers, are foley's ground truth.
		"-map_metadata", "-1",
		"-fflags", "+bitexact",
		"-flags:v", "+bitexact",
	}
	args = append(args, codecArgs...)
	args = append(args, outPath)
	return execx.Run(ctx, execx.FFmpeg, args...)
}

// readManifest parses a closed PNGSink's manifest into its total and
// last durations, adding in exact microsecond integers — the same
// decimal values ffmpeg parses, so the -t boundary lands exactly on the
// duplicate frame's timestamp.
func readManifest(framesDir string) (total, last time.Duration, err error) {
	raw, err := os.ReadFile(filepath.Join(framesDir, manifestName)) //nolint:gosec // fixed name inside the caller-owned frames dir
	if err != nil {
		return 0, 0, fmt.Errorf("encode: no manifest (did you Close the PNGSink?): %w", err)
	}
	return parseDurations(raw)
}

// parseMicros parses the manifest's exact "S.ffffff" decimal into
// integer microseconds — the same digits ffmpeg reads.
func parseMicros(val string) (int64, error) {
	sec, frac, ok := strings.Cut(val, ".")
	if !ok || len(frac) != 6 {
		return 0, errors.New("want S.ffffff")
	}
	s, err := strconv.ParseInt(sec, 10, 64)
	if err != nil {
		return 0, err
	}
	us, err := strconv.ParseInt(frac, 10, 64)
	if err != nil {
		return 0, err
	}
	return s*1_000_000 + us, nil
}

func parseDurations(manifest []byte) (total, last time.Duration, err error) {
	var totalMicros, lastMicros int64
	sc := bufio.NewScanner(bytes.NewReader(manifest))
	for sc.Scan() {
		line := sc.Text()
		val, ok := strings.CutPrefix(line, "duration ")
		if !ok {
			continue
		}
		micros, err := parseMicros(val)
		if err != nil {
			return 0, 0, fmt.Errorf("encode: malformed manifest duration %q: %w", line, err)
		}
		lastMicros = micros
		totalMicros += lastMicros
	}
	if err := sc.Err(); err != nil {
		return 0, 0, fmt.Errorf("encode: reading manifest: %w", err)
	}
	if totalMicros <= 0 {
		return 0, 0, fmt.Errorf("encode: manifest has no durations")
	}
	return time.Duration(totalMicros) * time.Microsecond,
		time.Duration(lastMicros) * time.Microsecond, nil
}
